### ISSUE TITLE
Uhm

### ISSUE THREAD

**Issue by ComradePie** [ConnorTron110/SCP-XK-Unity#4]
I don't know what to do after I download the mod ive downloaded it a few times and I don't know what to do now I don't know if this will will help or not but I am on windows 10...

**Comment by ConnorTron110** [comment]
This is not Bug related so im closing this issue, If you have any questions, then go [on our discord](https://discordapp.com/invite/QkWF48u), this is more for bug reporting.

However to answer your question you probably dont have forge installed, you will more than likely fix this issue with this [tutorial](https://www.youtube.com/watch?v=w57N12jGDcc)
