### ISSUE TITLE
the blinking effect

### ISSUE THREAD

**Issue by tomiscool850** [ConnorTron110/SCP-XK-Unity#8]
improvment

**Description:**
this is an effect that is caused from being to close to scp 173/blinking type scps in the futer. it would make your screen black every 3-5 seconds. 

**Reason:**
Its simple to make scp 173 more challenging.  in the game all you have to do is look at him whitch made him easy to doghe, but with this he will be harder.

**Comment by ConnorTron110** [comment]
Mechanic already under development, keep an eye out on the dev builds 👀
